import jsPDF from 'jspdf'
import { autoTable } from 'jspdf-autotable'

// ── Helpers ───────────────────────────────────────────────────────────────────

function hexToRgb(hex) {
  const r = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return r ? [parseInt(r[1], 16), parseInt(r[2], 16), parseInt(r[3], 16)] : [232, 98, 42]
}

function brandLight(b) {
  // Very light tint of brand (88% white blend)
  return b.map(c => Math.round(c * 0.12 + 255 * 0.88))
}

function fmtAmt(n) {
  return Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtMoney(n, currency = 'USD') {
  return `${currency} ${fmtAmt(n)}`
}

function fmtDate(iso) {
  if (!iso) return '—'
  const d = new Date(iso)
  return isNaN(d) ? iso : d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
}

async function loadImageAsDataUrl(url) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 5000)
  try {
    const resp = await fetch(url, { signal: controller.signal })
    const blob = await resp.blob()
    return await new Promise((res, rej) => {
      const reader = new FileReader()
      reader.onload  = () => res(reader.result)
      reader.onerror = rej
      reader.readAsDataURL(blob)
    })
  } catch { return null }
  finally { clearTimeout(timer) }
}

function imgFormat(dataUrl) {
  if (!dataUrl) return 'PNG'
  if (dataUrl.startsWith('data:image/jpeg') || dataUrl.startsWith('data:image/jpg')) return 'JPEG'
  if (dataUrl.startsWith('data:image/webp')) return 'WEBP'
  return 'PNG'
}

// ── Palette ────────────────────────────────────────────────────────────────────

const DARK       = [17,  24,  39]
const MID_GRAY   = [107, 114, 128]
const LIGHT_GRAY = [249, 250, 251]
const ALT_ROW    = [246, 247, 249]
const CAT_ROW    = [240, 242, 247]
const WHITE      = [255, 255, 255]
const RULE       = [229, 231, 235]

// ── Layout constants ───────────────────────────────────────────────────────────

const M           = 14    // page margin
const SIG_H       = 38    // signature block height
const FOOTER_H    = 7     // footer height
const RESERVE     = SIG_H + FOOTER_H + 2   // bottom reserve on every page
const MINI_H      = 10    // detail page mini-header height
const BAND_H      = 28    // Modern page-1 brand band height

// ── Signature block ────────────────────────────────────────────────────────────

function drawSignatureBlock(doc, pageW, pageH, clientName, settings, isLastPage) {
  const top  = pageH - SIG_H - FOOTER_H
  const midX = pageW / 2
  let y = top + 5

  doc.setDrawColor(...RULE)
  doc.setLineWidth(0.35)
  doc.line(M, top, pageW - M, top)

  // LEFT — Prepared by
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6)
  doc.setTextColor(...MID_GRAY)
  doc.text('PREPARED BY', M, y)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  doc.setTextColor(...DARK)
  doc.text(settings?.designer_name || '', M, y + 4.5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MID_GRAY)
  doc.text(settings?.designer_position || '', M, y + 9)

  const sigLineY = y + (isLastPage ? 21 : 15)
  doc.setDrawColor(...MID_GRAY)
  doc.setLineWidth(0.2)
  doc.line(M, sigLineY, midX - 12, sigLineY)
  doc.setFontSize(6)
  doc.text('Signature', M, sigLineY + 3)
  if (isLastPage) {
    doc.line(M, sigLineY + 9, midX - 12, sigLineY + 9)
    doc.text('Date', M, sigLineY + 12)
  }

  // RIGHT — Confirmed by
  const rx = midX + 8
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6)
  doc.setTextColor(...MID_GRAY)
  doc.text('CONFIRMED & ACCEPTED BY', rx, y)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  doc.setTextColor(...DARK)
  doc.text(clientName || 'Client', rx, y + 4.5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MID_GRAY)
  doc.text('Client', rx, y + 9)

  doc.setDrawColor(...MID_GRAY)
  doc.setLineWidth(0.2)
  doc.line(rx, sigLineY, pageW - M, sigLineY)
  doc.setFontSize(6)
  doc.text('Signature', rx, sigLineY + 3)
  if (isLastPage) {
    doc.line(rx, sigLineY + 9, pageW - M, sigLineY + 9)
    doc.text('Date', rx, sigLineY + 12)
  }
}

// ── Page footer ────────────────────────────────────────────────────────────────

function drawPageFooter(doc, pageNum, totalPages, pageW, pageH, layout) {
  const txt = `Generated by CatchQuote · catchquote.io     Page ${pageNum} of ${totalPages}`
  doc.setFontSize(6.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MID_GRAY)
  if (layout === 'modern') {
    doc.text(txt, pageW - M, pageH - 2, { align: 'right' })
  } else {
    doc.text(txt, pageW / 2, pageH - 2, { align: 'center' })
  }
}

// ── Continuation page mini-header ─────────────────────────────────────────────

function drawMiniHeader(doc, settings, quote, BRAND, pageW, layout) {
  if (layout === 'modern') {
    doc.setFillColor(...BRAND)
    doc.rect(0, 0, pageW, MINI_H, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...WHITE)
    doc.text(settings?.company_name || '', M, MINI_H - 2.8)
    doc.text(quote.quoteNumber || '', pageW - M, MINI_H - 2.8, { align: 'right' })
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7.5)
    doc.setTextColor(...DARK)
    doc.text(settings?.company_name || '', M, MINI_H - 3)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MID_GRAY)
    doc.text(quote.quoteNumber || '', pageW - M, MINI_H - 3, { align: 'right' })
    doc.setDrawColor(...RULE)
    doc.setLineWidth(0.35)
    doc.line(M, MINI_H, pageW - M, MINI_H)
  }
}

// ── Separator line ─────────────────────────────────────────────────────────────

function sepLine(doc, y, pageW) {
  doc.setDrawColor(...RULE)
  doc.setLineWidth(0.4)
  doc.line(M, y, pageW - M, y)
}

// ── Page 1 header — Classic ───────────────────────────────────────────────────

function drawPage1Classic(doc, settings, quote, BRAND, logoDataUrl, pageW) {
  const LOGO_H = 16
  let leftY    = 5

  // LEFT — logo or company name
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, imgFormat(logoDataUrl), M, leftY, 0, LOGO_H)
      leftY += LOGO_H + 3
    } catch { /* skip */ }
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(...DARK)
    doc.text(settings?.company_name || '', M, leftY + LOGO_H / 2 + 2.5)
    leftY += LOGO_H + 3
  }

  // RIGHT — company name + contact details stacked
  const rx          = pageW - M
  const lineH       = 4.5
  const contactParts = [settings?.company_address, settings?.company_phone, settings?.company_email].filter(Boolean)
  let rightY        = 7

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...DARK)
  doc.text(settings?.company_name || '', rx, rightY, { align: 'right' })
  rightY += lineH + 1

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...MID_GRAY)
  for (const part of contactParts) {
    doc.text(part, rx, rightY, { align: 'right' })
    rightY += lineH
  }
  if (settings?.company_registration) {
    doc.text(`Reg: ${settings.company_registration}`, rx, rightY, { align: 'right' })
    rightY += lineH
  }

  // Thin brand colour underline separating header from body
  const ruleY = Math.max(leftY, rightY) + 3
  doc.setDrawColor(...BRAND)
  doc.setLineWidth(1)
  doc.line(M, ruleY, pageW - M, ruleY)

  // QUOTATION title + quote meta below
  let y = ruleY + 9

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...BRAND)
  doc.text('QUOTATION', M, y)
  y += 4

  doc.setDrawColor(...RULE)
  doc.setLineWidth(0.4)
  doc.line(M, y, pageW - M, y)
  y += 6

  for (const [label, value] of [
    ['QUOTE NO.',   quote.quoteNumber || '—'],
    ['DATE',        fmtDate(quote.date)],
    ['VALID UNTIL', fmtDate(quote.validUntil)],
    ['CURRENCY',    quote.currency || 'USD'],
  ]) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...MID_GRAY)
    doc.text(label, M, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    doc.text(value, M + 36, y)
    y += 5
  }

  return y + 4
}

// ── Page 1 header — Modern ────────────────────────────────────────────────────

function drawPage1Modern(doc, settings, quote, BRAND, logoDataUrl, pageW) {
  // ── Brand band ──────────────────────────────────────────────────────────────
  doc.setFillColor(...BRAND)
  doc.rect(0, 0, pageW, BAND_H, 'F')

  // LEFT — logo (vertically centred) or company name if no logo
  const LOGO_H = 18
  const logoY  = (BAND_H - LOGO_H) / 2

  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, imgFormat(logoDataUrl), M, logoY, 0, LOGO_H)
    } catch { /* skip */ }
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.setTextColor(...WHITE)
    doc.text(settings?.company_name || '', M, BAND_H / 2 + 2.5)
  }

  // RIGHT — company name (bold) + address / phone / email stacked, all white
  const rx           = pageW - M
  const lineH        = 4.5
  const contactParts = [settings?.company_address, settings?.company_phone, settings?.company_email].filter(Boolean)
  const nLines       = 1 + contactParts.length + (settings?.company_registration ? 1 : 0)
  let rightY         = (BAND_H - nLines * lineH) / 2 + lineH

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...WHITE)
  doc.text(settings?.company_name || '', rx, rightY, { align: 'right' })
  rightY += lineH + 0.5

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...WHITE)
  for (const part of contactParts) {
    doc.text(part, rx, rightY, { align: 'right' })
    rightY += lineH
  }
  if (settings?.company_registration) {
    doc.text(`Reg: ${settings.company_registration}`, rx, rightY, { align: 'right' })
  }

  // ── Below band — QUOTATION title + quote meta ───────────────────────────────
  let y = BAND_H + 9

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...BRAND)
  doc.text('QUOTATION', M, y)
  y += 4

  doc.setDrawColor(...BRAND)
  doc.setLineWidth(0.6)
  doc.line(M, y, pageW - M, y)
  y += 6

  for (const [label, value] of [
    ['QUOTE NO.',   quote.quoteNumber || '—'],
    ['DATE',        fmtDate(quote.date)],
    ['VALID UNTIL', fmtDate(quote.validUntil)],
    ['CURRENCY',    quote.currency || 'USD'],
  ]) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...MID_GRAY)
    doc.text(label, M, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    doc.text(value, M + 36, y)
    y += 5
  }

  return y + 4
}

// ── Client / project block ─────────────────────────────────────────────────────

function drawClientBlock(doc, quote, settings, y, pageW) {
  const col2X = pageW / 2 + 6
  let leftY = y
  let rightY = y

  // Bill To
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6.5)
  doc.setTextColor(...MID_GRAY)
  doc.text('BILL TO', M, leftY)
  leftY += 4.5

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...DARK)
  doc.text(quote.clientName || '—', M, leftY)
  leftY += 5

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MID_GRAY)
  for (const txt of [quote.clientContact, quote.clientEmail, quote.clientAddress].filter(Boolean)) {
    const lines = doc.splitTextToSize(txt, col2X - M - 6)
    doc.text(lines, M, leftY)
    leftY += lines.length * 4
  }

  // Project address
  if (quote.projectAddress) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(...MID_GRAY)
    doc.text('PROJECT ADDRESS', col2X, rightY)
    rightY += 4.5
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...DARK)
    const pLines = doc.splitTextToSize(quote.projectAddress, pageW - M - col2X)
    doc.text(pLines, col2X, rightY)
    rightY += pLines.length * 4 + 2
  }

  // Sales designer
  const designer = quote.designerName || settings?.designer_name
  if (designer) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(6.5)
    doc.setTextColor(...MID_GRAY)
    doc.text('SALES DESIGNER', col2X, rightY)
    rightY += 4.5
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...DARK)
    doc.text(designer, col2X, rightY)
    rightY += 4
  }

  return Math.max(leftY, rightY)
}

// ── Summary section (page 1: summary table + totals) ──────────────────────────

function drawSummary(doc, areas, areaSubtotals, itemsByArea, subtotal, gst, gstEnabled, total, quote, settings, BRAND, layout, pageW, startY) {
  const cur = quote.currency || 'USD'
  let y = startY

  // Section title
  if (layout === 'modern') {
    doc.setFillColor(...BRAND)
    doc.rect(M, y, 3.5, 7.5, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(...BRAND)
    doc.text('SUMMARY OF WORKS', M + 7, y + 5.5)
    y += 13
  } else {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9.5)
    doc.setTextColor(...DARK)
    doc.text('SUMMARY OF WORKS', M, y + 5)
    sepLine(doc, y + 8, pageW)
    y += 13
  }

  const rows = areas
    .filter(a => (itemsByArea.get(a) ?? []).length > 0)
    .map(a => [a, fmtAmt(areaSubtotals.get(a) ?? 0)])

  const tableStartY = y

  autoTable(doc, {
    startY: y,
    head: [['Area of Works', `Subtotal (${cur})`]],
    body: rows,
    styles: {
      fontSize: 9,
      cellPadding: { top: 3.5, bottom: 3.5, left: 5, right: 5 },
      textColor: DARK,
      lineColor: RULE,
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: BRAND,
      textColor: WHITE,
      fontStyle: 'bold',
      fontSize: 8,
      lineWidth: 0,
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 42, halign: 'right', fontStyle: 'bold' },
    },
    alternateRowStyles: { fillColor: layout === 'modern' ? ALT_ROW : WHITE },
    margin: { left: M, right: M, bottom: RESERVE, top: MINI_H + 6 },
    didAddPage: () => drawMiniHeader(doc, settings, quote, BRAND, pageW, layout),
  })

  // Modern: brand left accent bar on summary table
  if (layout === 'modern') {
    doc.setFillColor(...BRAND)
    doc.rect(M, tableStartY, 3, doc.lastAutoTable.finalY - tableStartY, 'F')
  }

  y = doc.lastAutoTable.finalY + 8

  // Totals block
  const labelX = pageW - M - 72
  const valX   = pageW - M

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MID_GRAY)
  doc.text('Subtotal', labelX, y)
  doc.setTextColor(...DARK)
  doc.text(fmtMoney(subtotal, cur), valX, y, { align: 'right' })
  y += 6

  if (gstEnabled) {
    doc.setTextColor(...MID_GRAY)
    doc.text('GST (9%)', labelX, y)
    doc.setTextColor(...DARK)
    doc.text(fmtMoney(gst, cur), valX, y, { align: 'right' })
    y += 6
  }

  sepLine(doc, y - 1.5, pageW)
  y += 2

  const totalH = 9
  doc.setFillColor(...BRAND)
  doc.roundedRect(labelX - 4, y, valX - labelX + 6, totalH, 1, 1, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...WHITE)
  doc.text(`GRAND TOTAL (${cur})`, labelX, y + 6)
  doc.text(fmtMoney(total, cur), valX, y + 6, { align: 'right' })

  return y + totalH + 4
}

// ── One area's detail section ─────────────────────────────────────────────────

function drawArea(doc, areaName, areaItems, areaSubtotal, BRAND, layout, currency, pageW, pageH, settings, quote, startY) {
  let y = startY

  // Page break check before area header
  if (y + 40 > pageH - RESERVE) {
    doc.addPage()
    drawMiniHeader(doc, settings, quote, BRAND, pageW, layout)
    y = MINI_H + 4
  }

  const tableW = pageW - 2 * M
  const BL = brandLight(BRAND)

  // Area header bar
  if (layout === 'modern') {
    doc.setFillColor(...BL)
    doc.roundedRect(M, y, tableW, 8.5, 1.5, 1.5, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9.5)
    doc.setTextColor(...BRAND)
    doc.text(areaName.toUpperCase(), M + 5, y + 6)
    doc.text(fmtMoney(areaSubtotal, currency), pageW - M - 3, y + 6, { align: 'right' })
  } else {
    doc.setFillColor(...BRAND)
    doc.rect(M, y, tableW, 8, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9.5)
    doc.setTextColor(...WHITE)
    doc.text(areaName.toUpperCase(), M + 4, y + 5.5)
    doc.text(fmtMoney(areaSubtotal, currency), pageW - M - 3, y + 5.5, { align: 'right' })
  }
  y += (layout === 'modern' ? 11 : 10)

  // Group items by category
  const groups = []
  for (const item of areaItems) {
    const last = groups[groups.length - 1]
    if (!last || last.cat !== item.category) {
      groups.push({ cat: item.category, items: [] })
    }
    groups[groups.length - 1].items.push(item)
  }

  // Build autoTable body
  const body = []
  let itemNum = 0

  const catSubtotalStyle = {
    fontStyle: 'bold',
    halign: 'right',
    fillColor: layout === 'modern' ? [243, 244, 248] : [245, 247, 250],
    textColor: DARK,
    cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 },
    fontSize: 7.5,
  }

  const areaSubtotalStyle = {
    fontStyle: 'bold',
    halign: 'right',
    fillColor: BRAND,
    textColor: WHITE,
    cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
    fontSize: 8,
  }

  for (const { cat, items } of groups) {
    // Category header row
    body.push([{
      content:  cat,
      colSpan:  6,
      styles: {
        fillColor:   CAT_ROW,
        fontStyle:   layout === 'modern' ? 'normal' : 'bold',
        fontSize:    7.5,
        textColor:   MID_GRAY,
        cellPadding: { top: 2.5, bottom: 2.5, left: layout === 'modern' ? 10 : 5, right: 5 },
      },
    }])

    // Item rows
    for (const item of items) {
      itemNum++
      const lineTotal = (parseFloat(item.qty) || 0) * (parseFloat(item.unitPrice) || 0)
      const fill = (layout === 'modern' && itemNum % 2 === 0) ? ALT_ROW : WHITE
      body.push([
        { content: String(itemNum),            styles: { halign: 'center', textColor: MID_GRAY, fillColor: fill } },
        { content: item.description || '',     styles: { fillColor: fill } },
        { content: String(item.qty ?? ''),     styles: { halign: 'right', fillColor: fill } },
        { content: item.unit || '',            styles: { halign: 'center', fillColor: fill } },
        { content: fmtAmt(item.unitPrice),     styles: { halign: 'right', fillColor: fill } },
        { content: fmtAmt(lineTotal),          styles: { halign: 'right', fontStyle: 'bold', fillColor: fill } },
      ])
    }

    // Category subtotal
    const catSub = items.reduce((s, i) => s + (parseFloat(i.qty) || 0) * (parseFloat(i.unitPrice) || 0), 0)
    body.push([
      { content: `${cat} — Subtotal`, colSpan: 5, styles: catSubtotalStyle },
      { content: fmtAmt(catSub),                  styles: catSubtotalStyle },
    ])
  }

  // Area subtotal row
  body.push([
    { content: `${areaName} — Total`, colSpan: 5, styles: areaSubtotalStyle },
    { content: fmtAmt(areaSubtotal),              styles: areaSubtotalStyle },
  ])

  const headFill  = layout === 'modern' ? BRAND.map(c => Math.round(c * 0.82)) : BRAND
  const lineColor = layout === 'modern' ? [232, 234, 240] : RULE

  autoTable(doc, {
    startY: y,
    head:   [['No.', 'Description', 'Qty', 'Unit', `Unit Price (${currency})`, `Amount (${currency})`]],
    body,
    styles: {
      fontSize:    8.5,
      cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 },
      textColor:   DARK,
      lineColor,
      lineWidth:   0.2,
    },
    headStyles: {
      fillColor:  headFill,
      textColor:  WHITE,
      fontStyle:  'bold',
      fontSize:   7.5,
      lineWidth:  0,
    },
    columnStyles: {
      0: { cellWidth: 16,   halign: 'center' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 13,   halign: 'right'  },
      3: { cellWidth: 15,   halign: 'center' },
      4: { cellWidth: 30,   halign: 'right'  },
      5: { cellWidth: 30,   halign: 'right'  },
    },
    alternateRowStyles: { fillColor: WHITE },   // manual per-cell fill overrides this
    margin: { left: M, right: M, bottom: RESERVE, top: MINI_H + 6 },
    didAddPage: () => drawMiniHeader(doc, settings, quote, BRAND, pageW, layout),
  })

  return doc.lastAutoTable.finalY + 8
}

// ── Main export ────────────────────────────────────────────────────────────────

export async function exportQuotePDF({
  quote, areas, itemsByArea, areaSubtotals,
  subtotal, gst, gstEnabled, total,
  settings,
}) {
  const layout   = (settings?.pdf_layout || 'modern').toLowerCase()
  const BRAND    = hexToRgb(settings?.brand_colour || '#E8622A')
  const currency = quote.currency || 'USD'
  const pageW    = 210
  const pageH    = 297

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  let logoDataUrl = null
  if (settings?.company_logo_url) {
    logoDataUrl = await loadImageAsDataUrl(settings.company_logo_url).catch(() => null)
  }

  // ── PAGE 1: SUMMARY PAGE ──────────────────────────────────────────────────────

  let headerEnd
  if (layout === 'modern') {
    headerEnd = drawPage1Modern(doc, settings, quote, BRAND, logoDataUrl, pageW)
  } else {
    headerEnd = drawPage1Classic(doc, settings, quote, BRAND, logoDataUrl, pageW)
  }

  sepLine(doc, headerEnd + 2, pageW)

  const clientEnd = drawClientBlock(doc, quote, settings, headerEnd + 7, pageW)
  sepLine(doc, clientEnd + 4, pageW)

  let summaryEnd = drawSummary(
    doc, areas, areaSubtotals, itemsByArea,
    subtotal, gst, gstEnabled, total,
    quote, settings, BRAND, layout, pageW, clientEnd + 10
  )

  // Notes
  if (quote.notes) {
    let ny = summaryEnd + 4
    if (ny + 18 > pageH - RESERVE) { doc.addPage(); drawMiniHeader(doc, settings, quote, BRAND, pageW, layout); ny = MINI_H + 6 }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(...DARK)
    doc.text('Notes', M, ny)
    ny += 5
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MID_GRAY)
    for (const line of doc.splitTextToSize(quote.notes, pageW - M * 2)) {
      if (ny + 5 > pageH - RESERVE) { doc.addPage(); drawMiniHeader(doc, settings, quote, BRAND, pageW, layout); ny = MINI_H + 6 }
      doc.text(line, M, ny)
      ny += 4.5
    }
  }

  // ── DETAIL PAGES ─────────────────────────────────────────────────────────────

  const activeAreas = areas.filter(a => (itemsByArea.get(a) ?? []).length > 0)

  if (activeAreas.length > 0) {
    doc.addPage()
    drawMiniHeader(doc, settings, quote, BRAND, pageW, layout)
    let dy = MINI_H + 6

    // "DETAILED BREAKDOWN" section title
    if (layout === 'modern') {
      doc.setFillColor(...BRAND)
      doc.rect(M, dy, 3.5, 7.5, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor(...BRAND)
      doc.text('DETAILED BREAKDOWN', M + 7, dy + 5.5)
      dy += 14
    } else {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9.5)
      doc.setTextColor(...DARK)
      doc.text('DETAILED BREAKDOWN', M, dy + 5)
      sepLine(doc, dy + 8, pageW)
      dy += 14
    }

    for (const areaName of activeAreas) {
      const areaItems   = itemsByArea.get(areaName) ?? []
      const areaSubtotal = areaSubtotals.get(areaName) ?? 0
      dy = drawArea(doc, areaName, areaItems, areaSubtotal, BRAND, layout, currency, pageW, pageH, settings, quote, dy)
    }
  }

  // ── T&C PAGE ─────────────────────────────────────────────────────────────────

  if (settings?.terms_and_conditions?.trim()) {
    doc.addPage()
    drawMiniHeader(doc, settings, quote, BRAND, pageW, layout)
    let tcY = MINI_H + 6

    if (layout === 'modern') {
      doc.setFillColor(...BRAND)
      doc.rect(M, tcY, 3.5, 7.5, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(10)
      doc.setTextColor(...BRAND)
      doc.text('TERMS & CONDITIONS', M + 7, tcY + 5.5)
      tcY += 14
    } else {
      doc.setFillColor(...BRAND)
      doc.rect(M, tcY, pageW - M * 2, 8, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(...WHITE)
      doc.text('TERMS & CONDITIONS', M + 4, tcY + 5.5)
      tcY += 13
    }

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(55, 65, 81)

    for (const line of doc.splitTextToSize(settings.terms_and_conditions, pageW - M * 2)) {
      if (tcY + 5 > pageH - RESERVE) {
        doc.addPage()
        drawMiniHeader(doc, settings, quote, BRAND, pageW, layout)
        tcY = MINI_H + 6
      }
      doc.text(line, M, tcY)
      tcY += 4.5
    }
  }

  // ── PER-PAGE: signature + footer ──────────────────────────────────────────────

  const totalPages = doc.internal.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    drawSignatureBlock(doc, pageW, pageH, quote.clientName, settings, p === totalPages)
    drawPageFooter(doc, p, totalPages, pageW, pageH, layout)
  }

  const safeName = (quote.quoteNumber || 'quote').replace(/[^a-z0-9]/gi, '-').toLowerCase()

  // Yield the event loop before the synchronous deflate compression inside
  // doc.output('blob') so Supabase's token-refresh callbacks can run without
  // being starved by the blocking compression work.
  await new Promise(resolve => setTimeout(resolve, 0))

  // Use explicit blob output so we control the download trigger and release
  // the jsPDF instance (and its font/canvas buffers) before the browser's
  // deferred click fires — avoids the 40-second blob-URL lifetime that
  // jsPDF's built-in save() schedules internally.
  const blob = doc.output('blob')
  doc.internal = null   // allow GC to reclaim font and canvas buffers immediately

  const url = URL.createObjectURL(blob)
  const a   = document.createElement('a')
  a.href     = url
  a.download = `${safeName}.pdf`
  a.rel      = 'noopener'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Revoke after a short delay so the browser has started the download.
  setTimeout(() => URL.revokeObjectURL(url), 3000)
}
